services:
  veclim-data-server:
    container_name: "${VEC_NAME}"
    build:
      context: .
      args:
        VEC_PORTE: "${VEC_PORTE}"
    image: "${VEC_NAME}"
    restart: unless-stopped
    ports:
      - "${VEC_PORTE}:${VEC_PORT}"
    volumes:
      - "${VEC_DATA}:${DIR_DATA}"
    env_file:
      - .env

  veclim-data-server-nginx:
    image: nginx:stable
    container_name: "${VEC_NAME}-nginx"
    environment:
      - VEC_PORT=${VEC_PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache:/var/cache/nginx
    command: /bin/sh -c "envsubst < nginx.conf.template > nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "${VEC_PORTX}:80"
    depends_on:
      - veclim-data-server

volumes:
  nginx_cache:
